[package]
name = "parsec-tool"
version = "0.1.0"
authors = ["Contributors to the Parsec project"]
description = "Parsec Command Line Interface"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-tool"
readme = "README.md"
keywords = ["parsec", "cli", "tool"]
categories = ["development-tools", "command-line-utilities"]
edition = "2018"
documentation = "https://docs.rs/crate/parsec-tool"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0.31"
atty = "0.2"
clap = "3.0.0-beta.1"
parsec-client = "0.8.0"
parsec-interface = "0.20.0"
secrecy = { version = "0.6.0", features = ["serde"] }
structopt = "0.3.15"
thiserror = "1.0"

[lib]
name = "parsec_tool"
path = "src/lib.rs"

[[bin]]
name = "parsec-tool"
