[package]
name = "parsec-tool"
version = "0.1.0"
authors = ["Contributors to the Parsec project"]
description = "Parsec Command Line Interface"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-tool"
readme = "README.md"
keywords = ["parsec", "cli", "tool"]
categories = ["development-tools", "command-line-utilities"]
edition = "2018"
documentation = "https://docs.rs/crate/parsec-tool"

[dependencies]
