name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Execute CI script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute CI script
        run: ./ci.sh
